return {
	"catgoose/nvim-colorizer.lua",
	ft = {
		"css",
		"html",
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"vue",
		"python",
		"ruby",
		"markdown",
	},
	opts = {
		filetypes = { "*" },
		lazy_load = false,
		user_commands = true,
		user_default_options = {
			AARRGGBB = false,
			RGB = true,
			RGBA = true,
			RRGGBB = true,
			RRGGBBAA = true,
			always_update = false,
			hooks = { disable_line_highlight = false },
			hsl_fn = true,
			mode = "background",
			names = false,
			names_opts = { camelcase = true, lowercase = true, strip_digits = false, uppercase = false },
			oklch_fn = false,
			rgb_fn = true,
			sass = { enable = true, parsers = { "css" } },
			tailwind = "both",
			tailwind_opts = { update_names = true },
			xterm = false,
		},
	},
}
